name: domain_available
description: >-
  Checks if the domain is available. Use `Instant Domain Search Check`
  for check domain name.
repository: https://github.com/signmotion/domain_available
topics:
  - domain
  - checker
  - names
  - internet
  - tools

# Format:
#   version: major.minor.patch
# You can calculate the number version code by this formula:
#   code = m[A]jor * 100 * 100 + m[I]nor * 100 + [P]atch
# Otherwise: +AAIIPP
version: 0.1.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
